// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMSXmG9m2-d-lY47JL62jUJPXVXgWyvH4',
    appId: '1:172160805178:web:5df832d6891c1c58624803',
    messagingSenderId: '172160805178',
    projectId: 'myweather-a5143',
    authDomain: 'myweather-a5143.firebaseapp.com',
    storageBucket: 'myweather-a5143.appspot.com',
    measurementId: 'G-N89BQ1WNKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS7l9V1off1BfAUSCmRe2pmXH08M44zt8',
    appId: '1:172160805178:android:2c1b177e33d75561624803',
    messagingSenderId: '172160805178',
    projectId: 'myweather-a5143',
    storageBucket: 'myweather-a5143.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_uok1F3mBEmIcfcUnex8QWUGC93KzifU',
    appId: '1:172160805178:ios:20c69ca66787ce40624803',
    messagingSenderId: '172160805178',
    projectId: 'myweather-a5143',
    storageBucket: 'myweather-a5143.appspot.com',
    iosClientId: '172160805178-5heq1o77pb9bg5l7ncllu6cepimvd4ht.apps.googleusercontent.com',
    iosBundleId: 'com.example.sartUpProject',
  );
}
